CREATE TABLE sample(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	sex INT NOT NULL,
	age INT NOT NULL ,
	mother VARCHAR(100) NOT NULL,
	father VARCHAR(100) NOT NULL,
	win INT NOT NULL,
	lose INT NOT NULL,
	PRIMARY KEY(id)
);
